/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './poem.component.ngfactory';
import * as import2 from './poem.component';
import * as import3 from './poem.service';
import * as import4 from '@angular/common';
import * as import5 from './poem-list.component';
const styles_PoemListComponent:any[] = ([] as any[]);
export const RenderType_PoemListComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PoemListComponent,
  data: {}
}
);
function View_PoemListComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-poem',([] as any[]),(null as any),(null as any),(null as any),import1.View_PoemComponent_0,import1.RenderType_PoemComponent)),
      import0.ɵdid(49152,(null as any),0,import2.PoemComponent,[import3.PoemService],{poem: [
        0,
        'poem'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    const currVal_0:any = v.context.$implicit;
    ck(v,1,0,currVal_0);
  },(null as any));
}
export function View_PoemListComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'className',
        'col-md-8 col-md-offset-2'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_PoemListComponent_1)),
    import0.ɵdid(802816,(null as any),0,import4.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    var co:import5.PoemListComponent = v.component;
    const currVal_0:any = co.poems;
    ck(v,4,0,currVal_0);
  },(null as any));
}
function View_PoemListComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-poem-list',([] as any[]),(null as any),(null as any),(null as any),View_PoemListComponent_0,RenderType_PoemListComponent)),
    import0.ɵdid(114688,(null as any),0,import5.PoemListComponent,[import3.PoemService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const PoemListComponentNgFactory:import0.ComponentFactory<import5.PoemListComponent> = import0.ɵccf('app-poem-list',import5.PoemListComponent,View_PoemListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRHJvcGJveC9XZWJEZXYvVWRlbXkvYW5ndWxhcjRBbmROb2RlUHJhY3RpY2FsTWVhbkd1aWRlX2FnYWluL2NvdXJzZS1wcm9qZWN0L2Fzc2V0cy9hcHAvcG9lbXMvcG9lbS1saXN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Ecm9wYm94L1dlYkRldi9VZGVteS9hbmd1bGFyNEFuZE5vZGVQcmFjdGljYWxNZWFuR3VpZGVfYWdhaW4vY291cnNlLXByb2plY3QvYXNzZXRzL2FwcC9wb2Vtcy9wb2VtLWxpc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovRHJvcGJveC9XZWJEZXYvVWRlbXkvYW5ndWxhcjRBbmROb2RlUHJhY3RpY2FsTWVhbkd1aWRlX2FnYWluL2NvdXJzZS1wcm9qZWN0L2Fzc2V0cy9hcHAvcG9lbXMvcG9lbS1saXN0LmNvbXBvbmVudC50cy5Qb2VtTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovRHJvcGJveC9XZWJEZXYvVWRlbXkvYW5ndWxhcjRBbmROb2RlUHJhY3RpY2FsTWVhbkd1aWRlX2FnYWluL2NvdXJzZS1wcm9qZWN0L2Fzc2V0cy9hcHAvcG9lbXMvcG9lbS1saXN0LmNvbXBvbmVudC50cy5Qb2VtTGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgY2xhc3NOYW1lPVwiY29sLW1kLTggY29sLW1kLW9mZnNldC0yXCI+XG4gICAgICA8YXBwLXBvZW1cbiAgICAgICAgW3BvZW1dPVwicG9lbVwiXG4gICAgICAgICpuZ0Zvcj1cImxldCBwb2VtIG9mIHBvZW1zXCI+PC9hcHAtcG9lbT5cbiAgICA8L2Rpdj5cbiAgIiwiPGFwcC1wb2VtLWxpc3Q+PC9hcHAtcG9lbS1saXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDRU07a0JBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTs7O0lBQ0U7SUFERixTQUNFLFNBREY7Ozs7O0lBRk47TUFDSTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQTBDO0lBQ3hDO2dCQUFBOzs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBRXdDO0lBQ3BDOzs7O0lBREY7SUFGRixTQUVFLFNBRkY7Ozs7O0lDRk47Z0JBQUE7OztJQUFBOzs7In0=
