/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './logout.component';
import * as import2 from './auth.service';
import * as import3 from '@angular/router';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_LogoutComponent,
  data: {}
}
);
export function View_LogoutComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'col-md-8 col-md-offset-2'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'button',[[
        'class',
        'btn btn-danger'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.LogoutComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.onLogout()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Logout'])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(null as any),(null as any));
}
function View_LogoutComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-logout',([] as any[]),(null as any),(null as any),(null as any),View_LogoutComponent_0,RenderType_LogoutComponent)),
    import0.ɵdid(49152,(null as any),0,import1.LogoutComponent,[
      import2.AuthService,
      import3.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const LogoutComponentNgFactory:import0.ComponentFactory<import1.LogoutComponent> = import0.ɵccf('app-logout',import1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRHJvcGJveC9XZWJEZXYvVWRlbXkvYW5ndWxhcjRBbmROb2RlUHJhY3RpY2FsTWVhbkd1aWRlX2FnYWluL2NvdXJzZS1wcm9qZWN0L2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0Ryb3Bib3gvV2ViRGV2L1VkZW15L2FuZ3VsYXI0QW5kTm9kZVByYWN0aWNhbE1lYW5HdWlkZV9hZ2Fpbi9jb3Vyc2UtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0Ryb3Bib3gvV2ViRGV2L1VkZW15L2FuZ3VsYXI0QW5kTm9kZVByYWN0aWNhbE1lYW5HdWlkZV9hZ2Fpbi9jb3Vyc2UtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0Ryb3Bib3gvV2ViRGV2L1VkZW15L2FuZ3VsYXI0QW5kTm9kZVByYWN0aWNhbE1lYW5HdWlkZV9hZ2Fpbi9jb3Vyc2UtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTggY29sLW1kLW9mZnNldC0yXCI+XG4gICAgICA8YnV0dG9uIGNsYXNzPVwiYnRuIGJ0bi1kYW5nZXJcIiAoY2xpY2spPVwib25Mb2dvdXQoKVwiPkxvZ291dDwvYnV0dG9uPlxuICAgIDwvZGl2PiIsIjxhcHAtbG9nb3V0PjwvYXBwLWxvZ291dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNJO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBc0M7TUFDcEM7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUErQjtRQUFBO1FBQUE7TUFBQTtNQUEvQjtJQUFBO0lBQW9EO0lBQWU7Ozs7OztJQ0Z6RTtnQkFBQTs7O0lBQUE7S0FBQTs7OzsifQ==
