/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './message-input.component.ngfactory';
import * as import2 from './message-input.component';
import * as import3 from './message.service';
import * as import4 from './message-list.component.ngfactory';
import * as import5 from './message-list.component';
import * as import6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_MessagesComponent,
  data: {}
}
);
export function View_MessagesComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),10,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),7,'div',[[
        'class',
        'col-md-8 col-md-offset-2'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-input',([] as any[]),(null as any),(null as any),(null as any),import1.View_MessageInputComponent_0,import1.RenderType_MessageInputComponent)),
    import0.ɵdid(114688,(null as any),0,import2.MessageInputComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),(null as any),import4.View_MessageListComponent_0,import4.RenderType_MessageListComponent)),
    import0.ɵdid(114688,(null as any),0,import5.MessageListComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    ck(v,6,0);
    ck(v,9,0);
  },(null as any));
}
function View_MessagesComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-messages',([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,RenderType_MessagesComponent)),
    import0.ɵdid(49152,(null as any),0,import6.MessagesComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MessagesComponentNgFactory:import0.ComponentFactory<import6.MessagesComponent> = import0.ɵccf('app-messages',import6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRHJvcGJveC9XZWJEZXYvVWRlbXkvYW5ndWxhcjRBbmROb2RlUHJhY3RpY2FsTWVhbkd1aWRlX2FnYWluL2NvdXJzZS1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0Ryb3Bib3gvV2ViRGV2L1VkZW15L2FuZ3VsYXI0QW5kTm9kZVByYWN0aWNhbE1lYW5HdWlkZV9hZ2Fpbi9jb3Vyc2UtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0Ryb3Bib3gvV2ViRGV2L1VkZW15L2FuZ3VsYXI0QW5kTm9kZVByYWN0aWNhbE1lYW5HdWlkZV9hZ2Fpbi9jb3Vyc2UtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovRHJvcGJveC9XZWJEZXYvVWRlbXkvYW5ndWxhcjRBbmROb2RlUHJhY3RpY2FsTWVhbkd1aWRlX2FnYWluL2NvdXJzZS1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50LnRzLk1lc3NhZ2VzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGRpdiBjbGFzcz1cImNvbC1tZC04IGNvbC1tZC1vZmZzZXQtMlwiPlxuICAgICAgICA8YXBwLW1lc3NhZ2UtaW5wdXQ+PC9hcHAtbWVzc2FnZS1pbnB1dD5cbiAgICAgICAgPGFwcC1tZXNzYWdlLWxpc3Q+PC9hcHAtbWVzc2FnZS1saXN0PlxuICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gICIsIjxhcHAtbWVzc2FnZXM+PC9hcHAtbWVzc2FnZXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDSTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWlCO01BQ2Y7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFzQztJQUNwQztnQkFBQTtJQUF1QztJQUN2QztnQkFBQTtJQUFxQztJQUNqQztJQUNGOzs7SUFIRjtJQUNBOzs7OztJQ0pSO2dCQUFBOzs7OyJ9
